language: c
script: make check

compiler:
  - clang
  - gcc

sudo: required
dist: trusty
before_install:
 - sudo add-apt-repository ppa:mc3man/media-1 -y
 - sudo apt-get -qq update
 - sudo apt-get install -y libcmocka-dev
